### ISSUE TITLE
Pick a license for this

### ISSUE THREAD

**Issue by lubien** [lubien/fgo-calculations#1]

**Comment by renato04** [comment]
I would like to take this issue

**Comment by lubien** [comment]
Sure. Any suggestions?

**Comment by renato04** [comment]
MIT Licence?
But there is a license file in the repository. Do you want to change that?
Or Add another Licence file?

**Comment by lubien** [comment]
> MIT Licence?

The problem is that this is not software. That's why I want to change the current license too but I'm clueless

**Comment by renato04** [comment]
I think [GPL-3.0](https://opensource.org/licenses/GPL-3.0) fit your propose. Because it has some point about the documentation stuff.

What do you think?

**Comment by lubien** [comment]
> What do you think?

Perfect! Can you make a PR to change?

**Comment by renato04** [comment]
Yes! I'll do it
